version: '3.6'
services:
  # PostgreSQL
  postgres:
    container_name: postgres
    image: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/face-recognition-db
      POSTGRES_DB: face-recognition-db
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend API
  face-recognition-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-recognition-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/face-recognition-db
      REDIS_URI: redis://redis:6379
      API_CLARIFAI: e25d4397564b4d5abbfa90da26bb9c4d
      JWT_KEY: tacomtudoemcima
      PORT: "3000"
    links:
      - postgres
      - redis


    
      
  